# Generated by Django 4.0.1 on 2022-01-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='header_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Head Image'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='main_text',
            field=models.TextField(blank=True, verbose_name='Post content'),
        ),
    ]
