# Generated by Django 4.0.1 on 2022-01-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_posts_header_image_postheadimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='head_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Head image'),
        ),
        migrations.DeleteModel(
            name='PostHeadImage',
        ),
    ]
