# Generated by Django 4.0.1 on 2022-01-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_posts_head_image_delete_postheadimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='head_image',
        ),
    ]
