# Generated by Django 4.0.1 on 2022-01-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_posts_head_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Publication date'),
        ),
    ]
